disabled_rules:
  - identifier_name
line_length: 200
nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10
cyclomatic_complexity:
  warning: 25
  error: 50
